name: Deploy freshdatasource.com website to server

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Create SSH config folder
        run: mkdir -pv ~/.ssh

      - name: Add Known Hosts
        run: |
          echo "${{ secrets.SSH_DEPLOY_HOST_KEY }}" > ~/.ssh/known_hosts

      - name: Add SSH key
        run: |
          touch ~/.ssh/key
          chmod 600 ~/.ssh/key
          echo "${{ secrets.SSH_DEPLOY_RUNNER_KEY }}" > ~/.ssh/key

      - name: Clear directory on remote server
        # -q is required to remove IP leakage when warning about adding the SSH host key that is already kwnown
        # We are using a temporary directory (HOME) in case something goes belly up and to limit downtime. We wouldn't want there to be no website, would we?
        # This command is known to fail because it tried to delete the current directory . and the previous directory .. so we force it with true (remote)
        run: ssh -i ~/.ssh/key "${{ secrets.SSH_DEPLOY_DESTINATION }}"
          'rm -rf ~/* ~/.*; true'

      - name: Send to remote server
        run: scp -q -i ~/.ssh/key -r $GITHUB_WORKSPACE/web-interface/* "${{ secrets.SSH_DEPLOY_DESTINATION }}":~/

      - name: Deploy on the remote server
        run: ssh -q -i ~/.ssh/key "${{ secrets.SSH_DEPLOY_DESTINATION }}"
          'rm -rf /var/www/html/* &&
          mv ~/* /var/www/html'
